leftnav:
- identifier: 56525289-ed0c-6181-e21b-33d89ed325ee
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 44605915-67ff-38ae-d4ec-ceae6216cefd
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: external-ac038aa6bb4c49f0ac86e047ea4bc05a
  name: Online Publication
  url: https://biology.mit.edu/undergraduate/current-students/subject-offerings/covid-19-sars-cov-2-and-the-pandemic/
  weight: 1000
